### ISSUE TITLE
release 1.2 (sdist) broken on pypi ?

### ISSUE THREAD

**Issue by powo** [fiorix/cyclone#185]
Pypi reports Source and Binary packages from Nov 5 but the Source-Package seems to be older(broken) version ?

```
[root@bf1c18f37319 /]# /tmp/py/bin/pip install cyclone --no-binary :all:
Collecting cyclone
  Using cached https://files.pythonhosted.org/packages/5f/41/e9a4ee912395bd3efd96e7b62c9ff4ab61f794e59f0409163b153ab5eb42/cyclone-1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fzlVpy/cyclone/setup.py", line 44, in <module>
        if is_redhat and version and StrictVersion(version) < StrictVersion('6.0'):
    NameError: name 'StrictVersion' is not defined
```

vs.

```
[root@bf1c18f37319 /]# /tmp/py/bin/pip install cyclone 
Collecting cyclone
  Using cached https://files.pythonhosted.org/packages/5b/77/e457b0199c14bcf63533eeb5fe1d6ac655424e00146a378203e84cf79c61/cyclone-1.2-py2-none-any.whl
Installing collected packages: cyclone
Successfully installed cyclone-1.2
```

**Comment by fiorix** [comment]
Not sure what's going on, no time to troubleshoot this.

**Comment by fiorix** [comment]
Timeout
